server:
  port: 8443
  ssl:
    enabled: true
    bundle: "server-a"

spring:
  application:
    name: vault-ssl-test-app
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: demo-root-token
      kv:
        enabled: true
        backend: secret
        default-context: ssl-certs

  ssl:
    bundle:
      pem:
        server-a:
          reload-on-update: false
          keystore:
            certificate: "vault:secret/data/ssl-certs/server-a:certificate"
            private-key: "vault:secret/data/ssl-certs/server-a:private-key"
          truststore:
            certificate: "vault:secret/data/ssl-certs/server-a"

# Logging configuration
logging:
  level:
    org.springframework.vault: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http.client: DEBUG
